<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_REQUIREMENTS</name>
   <tag></tag>
   <elementGuidId>03c614eb-c062-4577-ad2f-1eede1083088</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='#requirements']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c21a2c44-e1e2-44b2-9369-2206f4a72b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#requirements</value>
      <webElementGuid>a9735cdb-1158-4ae5-baea-958847ea1972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>#requirements</value>
      <webElementGuid>5b6d2cdd-7c0c-423d-b4ef-001b8dd3f803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REQUIREMENTS</value>
      <webElementGuid>05974198-e15c-4710-a05a-76da4320985d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-3&quot;)/a[@id=&quot;#requirements&quot;]</value>
      <webElementGuid>b77b5b2c-c55d-4f52-abe1-1f805539d4f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='#requirements']</value>
      <webElementGuid>c3b16bab-e468-46f3-b1fd-2b31bf715417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h4[@id='ui-id-3']/a</value>
      <webElementGuid>aa005d1c-ca5b-4e3c-aa25-428166876689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'REQUIREMENTS')]</value>
      <webElementGuid>ca577dc1-b2fa-4d3d-80dd-ba5c59eb0bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cheque book'])[1]/following::a[1]</value>
      <webElementGuid>979be122-641c-409c-8164-c98273cc3fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email/SMS Alertz'])[1]/following::a[1]</value>
      <webElementGuid>f2ade0c8-1979-4f3b-b03d-a662b2ffd177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account opening form duly completed'])[1]/preceding::a[1]</value>
      <webElementGuid>6d8cd069-20c1-456b-9f52-fde64c91117b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One recent clear passport photograph of signatory'])[1]/preceding::a[1]</value>
      <webElementGuid>05e575f4-d4aa-464c-addc-dd81a097758c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REQUIREMENTS']/parent::*</value>
      <webElementGuid>ba4fb460-3778-4d42-9779-aa7d95cb87a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#requirements')])[3]</value>
      <webElementGuid>ba1cfcc5-dc7f-4738-819c-0ca20d6894f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h4/a</value>
      <webElementGuid>9992f6c3-d8a2-4705-bc5b-24cc79bbbad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#requirements' and @id = '#requirements' and (text() = 'REQUIREMENTS' or . = 'REQUIREMENTS')]</value>
      <webElementGuid>308c46ba-c027-4a21-9c8c-78a276b95b67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
